import heroImg from './assets/images/wonderlust_hero_1779974724512.png';
import surfImg from './assets/images/wonderlust_surf_1779974747087.png';
import kashmirImg from './assets/images/wonderlust_kashmir_1779974768619.png';
import baliImg from './assets/images/wonderlust_bali_1779974793737.png';
import textureImg from './assets/images/wonderlust_texture_1779974813611.png';
import { Destination } from './types';

export const DESTINATIONS: Destination[] = [
  {
    id: 'thailand',
    name: 'Koh Phi Phi',
    nameId: 'Koh Phi Phi',
    country: 'Thailand',
    countryId: 'Thailand',
    rating: 4.9,
    reviewsCount: 142,
    pricePerPerson: 1050.00,
    image: heroImg,
    description: 'A paradise with crystal clear turquoise pristine waters, gorgeous resort piers, sandy shores, and vibrant snorkeling coral lagoons.',
    descriptionId: 'Surga dengan air laut pirus kristal yang murni, dermaga resor yang megah, pantai berpasir, dan laguna karang snorkeling yang semarak.',
    durationDays: 7,
  },
  {
    id: 'kashmir',
    name: 'Snowcapped Valley',
    nameId: 'Lembah Bersalju',
    country: 'Kashmir',
    countryId: 'Kashmir',
    rating: 5.0,
    reviewsCount: 218,
    pricePerPerson: 670.50,
    image: kashmirImg,
    description: 'Marvelous deep valley flanked by snow crowned Himalayan peak ranges, gorgeous dark pine forests, and atmospheric cool mornings.',
    descriptionId: 'Lembah dalam menakjubkan yang diapit oleh pegunungan bersalju puncak Himalaya, hutan pinus gelap yang indah, dan pagi sejuk atmosferik.',
    durationDays: 5,
  },
  {
    id: 'bali',
    name: 'Seminyak Beach Resort',
    nameId: 'Resor Pantai Seminyak',
    country: 'Bali, Indonesia',
    countryId: 'Bali, Indonesia',
    rating: 4.8,
    reviewsCount: 340,
    pricePerPerson: 890.00,
    image: baliImg,
    description: 'Summertime beachfront luxury featuring pristine tropical pool views, parking seaplanes, surf breaks, and magnificent pink sunsets.',
    descriptionId: 'Kemewahan tepi pantai musim panas yang menampilkan pemandangan kolam tropis murni, tempat parkir pesawat amfibi, ombak selancar, dan matahari terbenam merah muda yang menakjubkan.',
    durationDays: 6,
  },
  {
    id: 'surf-paradise',
    name: 'Malibu Wave Breaks',
    nameId: 'Ombak Malibu',
    country: 'Malibu, USA',
    countryId: 'Malibu, Amerika Serikat',
    rating: 4.7,
    reviewsCount: 98,
    pricePerPerson: 540.00,
    image: surfImg,
    description: 'Catch clean pipelines on custom twin-fin designer boards over gorgeous shimmering green waves with cinematic golden sunlight.',
    descriptionId: 'Nikmati gulungan ombak bersih dengan papan selancar twin-fin kustom desainer di atas ombak hijau berkilau yang indah dengan cahaya matahari keemasan sinematik.',
    durationDays: 4,
  },
  {
    id: 'maldives',
    name: 'Luxury Overwater Villas',
    nameId: 'Vila Atas Air Mewah',
    country: 'Maldives',
    countryId: 'Maladewa',
    rating: 4.9,
    reviewsCount: 165,
    pricePerPerson: 1540.00,
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80',
    description: 'Experience pure glass floor bungalow views, exclusive infinity pools, private seaplane transfers, and personal marine butler assistance in the Indian Ocean.',
    descriptionId: 'Nikmati pemandangan bungalow lantai kaca murni, kolam tanpa batas eksklusif, antar-jemput pesawat amfibi pribadi, dan asisten pelayan kelautan pribadi di Samudra Hindia.',
    durationDays: 7,
  },
  {
    id: 'swiss-alps',
    name: 'Swiss Alps Cedar Chalet',
    nameId: 'Chalet Kayu Cedar Alpen',
    country: 'Switzerland',
    countryId: 'Swiss',
    rating: 5.0,
    reviewsCount: 112,
    pricePerPerson: 1250.00,
    image: 'https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=800&q=80',
    description: 'Tuck yourself inside custom high-end cedar chalets featuring private thermal spas, panoramic snowy mountain terraces, and personal ski guides.',
    descriptionId: 'Hangatkan diri Anda di dalam chalet kayu cedar kelas atas yang mewah menampilkan spa termal pribadi, teras pegunungan bersalju panoramik, dan panduan ski pribadi.',
    durationDays: 5,
  },
  {
    id: 'kyoto-zen',
    name: 'Kyoto Zen Forest Retreat',
    nameId: 'Retret Hutan Zen Kyoto',
    country: 'Japan',
    countryId: 'Jepang',
    rating: 4.9,
    reviewsCount: 198,
    pricePerPerson: 950.00,
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
    description: 'Reconnect with silent wellness inside towering bamboo forests, private natural hot spring onsens, and award-winning traditional kaiseki tea ceremonies.',
    descriptionId: 'Terhubung kembali dengan kesehatan hening di dalam hutan bambu menjulang tinggi, onsen air panas alami pribadi, dan upacara teh kaiseki tradisional pemenang penghargaan.',
    durationDays: 6,
  },
  {
    id: 'santorini-suite',
    name: 'Santorini Caldera Cave Suite',
    nameId: 'Suite Gua Kaldera Santorini',
    country: 'Greece',
    countryId: 'Yunani',
    rating: 4.8,
    reviewsCount: 220,
    pricePerPerson: 1100.00,
    image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80',
    description: 'Cling premium white-washed luxury cave dwellings overlooking spectacular blue volcano bays, private plunge pools, and sunset cruises.',
    descriptionId: 'Nikmati hunian gua mewah bercat putih premium yang menghadap ke teluk gunung berapi biru spektakuler, kolam selam pribadi, dan pelayaran matahari terbenam.',
    durationDays: 4,
  }
];

export const IMAGES = {
  hero: heroImg,
  surf: surfImg,
  kashmir: kashmirImg,
  bali: baliImg,
  texture: textureImg,
};
