export const formatPrice = (priceInUsd: number, lang: 'en' | 'id'): string => {
  if (lang === 'id') {
    const rupiah = Math.round(priceInUsd * 15000);
    return 'Rp ' + rupiah.toLocaleString('id-ID');
  }
  return '$' + priceInUsd.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
};

// Simple translations dictionary to cover all UI elements
export const TRANSLATIONS = {
  en: {
    explore: 'Explore',
    packages: 'Packages',
    popular: 'Popular',
    contact: 'Contact Us',
    login: 'Login',
    register: 'Register',
    inquiries: 'Inquiries',
    heritage: 'Year Heritage',
    rating: 'Five-Star Rating',
    trips: 'Trips Accomplished',
    vipSupport: 'VIP Assistance',
    journal: 'Wanderlust Journal',
    journalDesc: 'Subscribe to unlock periodic secret discounts, priority resort openings, and exclusive custom itineraries.',
    join: 'Join',
    subscribed: '✓ Registered successfully inside archive!',
    footerDesc: 'Connecting wanderers with high-end luxury resort accommodation and authentic travel design. Certified members of the Global Sustainable Travel Alliance.',
    privacy: 'Privacy Policy',
    terms: 'Terms of Luxury Service',
    compliance: 'Environmental Compliance',
    allRights: 'Wonderlust Luxury Resorts Inc. All Rights Reserved.',

    // Hero Translation Objects
    exploreDream: 'EXPLORE,',
    dreamDiscover: 'DREAM, DISCOVER.',
    adventureCalls: 'The Adventure Calls',
    introText: 'Wonderlust: Your gateway to extraordinary adventures. Curated journeys that captivate your spirit and broaden your horizons.',
    featuredVacation: 'FEATURED VACATION',
    exploreThWithUs: 'Explore',
    withUs: 'With Us',
    discoverLocal: 'Discover local packages',
    destination: 'Destination',
    rooms: 'Rooms',
    persons: 'Persons',
    searchTour: 'Search Tour',
    findingTours: 'Finding Tours...',

    // TourGrid
    wonders: 'Wonderlust Wonders',
    unveiling: 'Unveiling handcrafted premium adventures tailored to feed your deepest curiosities.',
    curatedArchives: 'CURATED ARCHIVES',
    noMatches: 'No matching destination found',
    noMatchesDesc: 'We couldn\'t locate specific matches for "{term}". Browse our classic wonders catalog instead!',
    designCustom: 'Design Custom Tour',
    daysNights: 'Days / Nights Included',
    fareRates: 'Fare Rates',
    totalRate: 'Total Rate Estimate',
    inquireNow: 'Inquire Now',
    days: 'Days',
    stay: 'Stay',
    premiumInsurance: 'Premium Insurance',
    privateConcierge: 'Private Concierge Assistant',

    // Narrative
    tourYear: 'Our Tour In 2026/2027',
    glimpseBali: 'A Glimpse into Summertime in Bali',
    baliNarrative: '"Summertime in Bali is a tropical paradise, with golden beaches, crystal-clear waters, and lush green landscapes. The island buzzes with vibrant cultural festivals, world-class surfing, and stunning sunsets. Explore ancient temples, indulge in spa retreats, and savor delicious cuisine, making it a perfect escape for relaxation and adventure."',
    moreNarrative: 'At Wonderlust, we tailor every itinerary meticulously to bridge physical tranquility with deep spirit explorations. Whether you desire high-angle sea resorts, paddleboarding under amber morning horizons, or a personal certified field concierge, our travel designers provide an unmatched lifestyle voyage.',
    browseSchedules: 'Browse Schedules',
    travelersSelected: 'Travelers selected this season',

    // Contact Form
    expertAdvice: 'VIP EXPERT ADVICE',
    conciergeTitle: 'Wonderlust Concierge',
    conciergeText: 'Have questions about customized tours, resort configurations, or private flights? Connect with our personal travel designers. We response within two hours.',
    headquarters: 'Global Headquarters',
    hotline: 'Luxury Hotline',
    directAssistance: 'Direct Inquiries',
    secureTerms: 'YOUR PERSONAL REPUTATION, AND TRIPS HISTORY IS SECURED UNDER SHA-256 ENCRYPTED STANDARDS.',
    fullName: 'Full Name',
    luxuryEmail: 'Luxury Email',
    desiredSpot: 'Desired Spot',
    preferredDate: 'Preferred Date',
    roomsRequired: 'Rooms Required',
    adventurers: 'Adventurers',
    specialReq: 'Inquiry Message / Special Guidelines',
    specialPlaceholder: 'Tell us about details... e.g. Private ocean deck requests, special food diets, sunset boat hire...',
    submitting: 'Transmitting Inquiry...',
    submitBtn: 'Submit Inquiry Request',
    successTitle: 'Inquiry Lodged Successfully',
    successText: 'Thank you for trusting Wonderlust. Your secure reservation voucher ID has been logged in our regional system. A senior Concierge Assistant with specialized destination background will review and connect with you via email shortly!',
    voucherId: 'Voucher ID',
    activeStatus: 'Active Status',
    waitingRep: 'Awaiting Representative',
    sendAnother: 'Send another request',

    // Dashboard drawer
    inquiryLogs: 'Inquiry Logs',
    conciergeAccount: 'Concierge Account',
    vipPortal: 'VIP Member Standard Portal',
    activeInquiries: 'Your Active Enquiries',
    noVouchers: 'No active vouchers logged',
    noVouchersDesc: 'Submit our Concierge Service form to request special assistance or booking tickets!',
    submittedOn: 'Submitted on',
    guests: 'Guests',
    secureDesk: 'VIP SECURE CHANNEL DESK',
    resumeBrowsing: 'Resume Browsing'
  },
  id: {
    explore: 'Jelajahi',
    packages: 'Paket',
    popular: 'Populer',
    contact: 'Hubungi Kami',
    login: 'Masuk',
    register: 'Daftar',
    inquiries: 'Permintaan',
    heritage: 'Tahun Warisan',
    rating: 'Penilaian Bintang Lima',
    trips: 'Perjalanan Terselesaikan',
    vipSupport: 'Bantuan VIP',
    journal: 'Jurnal Wonderlust',
    journalDesc: 'Berlangganan untuk membuka diskon rahasia berkala, pembukaan prioritas resor, dan jadwal kustom eksklusif.',
    join: 'Ikut',
    subscribed: '✓ Berhasil terdaftar di dalam arsip!',
    footerDesc: 'Menghubungkan para pelancong dengan akomodasi resor mewah kelas atas dan desain perjalanan autentik. Anggota bersertifikat dari Aliansi Perjalanan Berkelanjutan Global.',
    privacy: 'Kebijakan Privasi',
    terms: 'Ketentuan Layanan Mewah',
    compliance: 'Kepatuhan Lingkungan',
    allRights: 'Wonderlust Luxury Resorts Inc. Seluruh Hak Cipta Dilindungi.',

    // Hero
    exploreDream: 'JELAJAHI,',
    dreamDiscover: 'IMPIKAN, TEMUKAN.',
    adventureCalls: 'Petualangan Memanggil',
    introText: 'Wonderlust: Gerbang Anda menuju petualangan luar biasa. Perjalanan pilihan terpilih yang menawan jiwa dan memperluas cakrawala Anda.',
    featuredVacation: 'LIBURAN UNGGULAN',
    exploreThWithUs: 'Jelajahi',
    withUs: 'Bersama Kami',
    discoverLocal: 'Temukan paket wisata lokal',
    destination: 'Destinasi Wisata',
    rooms: 'Kamar',
    persons: 'Orang / Tamu',
    searchTour: 'Cari Wisata',
    findingTours: 'Mencari Wisata...',

    // TourGrid
    wonders: 'Keajaiban Wonderlust',
    unveiling: 'Mengungkap petualangan premium buatan tangan yang disesuaikan untuk memuaskan rasa ingin tahu terdalam Anda.',
    curatedArchives: 'ARSIP PILIHAN',
    noMatches: 'Destinasi tidak ditemukan',
    noMatchesDesc: 'Kami tidak dapat menemukan hasil pencarian khusus untuk "{term}". Silakan jelajahi katalog klasik kami!',
    designCustom: 'Rancang Tur Kustom',
    daysNights: 'Hari / Malam Termasuk',
    fareRates: 'Tarif Biaya',
    totalRate: 'Estimasi Total Tarif',
    inquireNow: 'Kirim Permintaan',
    days: 'Hari',
    stay: 'Menginap',
    premiumInsurance: 'Asuransi Premium',
    privateConcierge: 'Asisten Layanan Pramutamu Pribadi',

    // Narrative
    tourYear: 'Tur Kami Di Tahun 2026/2027',
    glimpseBali: 'Sekilas tentang Musim Panas di Bali',
    baliNarrative: '"Musim panas di Bali adalah surga tropis, dengan pantai keemasan, air yang jernih, dan pemandangan rumbun hijau yang luas. Pulau ini semarak dengan festival budaya, selancar kelas dunia, dan matahari terbenam yang memukau. Jelajahi kuil kuno, manjakan diri di retret spa, dan nikmati kuliner lezat, menjadikannya pelarian sempurna untuk relaksasi dan petualangan."',
    moreNarrative: 'Di Wonderlust, kami merancang setiap rencana perjalanan dengan cermat untuk menyelaraskan ketenangan fisik dengan eksplorasi spiritual yang mendalam. Baik Anda menginginkan resor laut pemandangan tinggi, selancar dayung di bawah ufuk fajar jingga, atau asisten pramutamu berlisensi pribadi, desainer perjalanan kami menghadirkan perjalanan hidup yang tiada tanding.',
    browseSchedules: 'Lihat Jadwal',
    travelersSelected: 'Pelancong memilih musim ini',

    // Contact Form
    expertAdvice: 'KONSULTASI VIP AHLI',
    conciergeTitle: 'Layanan Resepsionis Wonderlust',
    conciergeText: 'Punya pertanyaan tentang tur kustom, spesifikasi resor, atau penerbangan pribadi? Hubungi desainer perjalanan pribadi kami. Kami merespons dalam waktu dua jam.',
    headquarters: 'Kantor Pusat Global',
    hotline: 'Hotline Kemewahan',
    directAssistance: 'Hubungan Langsung',
    secureTerms: 'REPUTASI PRIBADI DAN RIWAYAT PERJALANAN ANDA DIJAMIN AMAN DENGAN STANDAR ENKRIPSI SH-256 SECARA AMAN.',
    fullName: 'Nama Lengkap',
    luxuryEmail: 'Email Mewah',
    desiredSpot: 'Lokasi Pilihan',
    preferredDate: 'Tanggal Perjalanan',
    roomsRequired: 'Kamar yang Diperlukan',
    adventurers: 'Jumlah Pelancong',
    specialReq: 'Pesan Pertanyaan / Panduan Khusus',
    specialPlaceholder: 'Beri tahu kami detailnya... misal: permintaan dek dek laut pribadi, menu diet khusus, sewa katamaran saat matahari terbenam...',
    submitting: 'Mengirimkan Permintaan...',
    submitBtn: 'Kirim Formulir Pertanyaan Wisata',
    successTitle: 'Formulir Berhasil Dikirim',
    successText: 'Terima kasih telah memercayai Wonderlust. ID voucher pengajuan aman Anda telah terdaftar di sistem pusat kami. Asisten Senior Pramutamu kami akan menganalisis dan segera menghubungi Anda melalui email!',
    voucherId: 'ID Voucher',
    activeStatus: 'Status Aktif',
    waitingRep: 'Menunggu Tanggapan Staf',
    sendAnother: 'Kirim permintaan lain',

    // Dashboard drawer
    inquiryLogs: 'Log Permintaan Anda',
    conciergeAccount: 'Akun Layanan Pramutamu',
    vipPortal: 'Portal Standar Anggota VIP',
    activeInquiries: 'Permintaan Aktif Anda',
    noVouchers: 'Tidak ada voucher aktif terdaftar',
    noVouchersDesc: 'Silakan isi formulir Layanan Pramutamu kami untuk mengajukan layanan khusus atau pesan tiket perjalanan!',
    submittedOn: 'Diajukan pada',
    guests: 'Tamu',
    secureDesk: 'VIP SECURE CHANNEL DESK',
    resumeBrowsing: 'Lanjutkan Penjelajahan'
  }
};
